// Generated by scripts/build_perspective_viewer.py; do not edit by hand.
window.DELHI_VIEWER_DATA = Object.freeze({
  "image": {
    "width": 2799,
    "height": 1960,
    "url": "delhi_before_siege_illustration.webp"
  },
  "crs": "EPSG:32643",
  "cityMaskPixels": [
    [
      145,
      505
    ],
    [
      650,
      440
    ],
    [
      1200,
      420
    ],
    [
      1900,
      425
    ],
    [
      2200,
      440
    ],
    [
      2390,
      520
    ],
    [
      2615,
      690
    ],
    [
      2300,
      1050
    ],
    [
      1850,
      1210
    ],
    [
      1440,
      1390
    ],
    [
      990,
      1430
    ],
    [
      250,
      1390
    ]
  ],
  "globalAffine": [
    [
      -1.2736922204627694,
      -0.4156888907788243,
      720257.3504852703
    ],
    [
      0.44704680735099556,
      2.821292147778422,
      3168692.816592621
    ],
    [
      0.0,
      0.0,
      1.0
    ]
  ],
  "naturalRegions": [
    {
      "name": "Fort and northern wall",
      "centre": [
        760.0,
        1160.0
      ],
      "scale": [
        720.0,
        520.0
      ],
      "matrix": [
        [
          -1.3621123616422508,
          -0.353626758767291,
          720287.8264076511
        ],
        [
          0.43977472936091194,
          2.7281582624787006,
          3168795.4264831045
        ],
        [
          0.0,
          0.0,
          1.0
        ]
      ]
    },
    {
      "name": "Chandni Chowk and western city",
      "centre": [
        1780.0,
        1010.0
      ],
      "scale": [
        760.0,
        540.0
      ],
      "matrix": [
        [
          -1.3004458927079685,
          -0.5094503858817916,
          720378.4132446778
        ],
        [
          0.45107417326522276,
          2.7996997281939002,
          3168710.691964522
        ],
        [
          0.0,
          0.0,
          1.0
        ]
      ]
    },
    {
      "name": "Jama Masjid and southern gates",
      "centre": [
        1430.0,
        590.0
      ],
      "scale": [
        900.0,
        430.0
      ],
      "matrix": [
        [
          -1.2128030463200585,
          -0.34316826890847096,
          720115.9438380301
        ],
        [
          0.4629525494078886,
          2.9596390226406584,
          3168563.4504580055
        ],
        [
          0.0,
          0.0,
          1.0
        ]
      ]
    }
  ],
  "anchors": [
    {
      "legend": 4,
      "name": "Salimgarh Fort",
      "legendText": "Selimghur, an ancient fort",
      "pixel": [
        385.0,
        1310.0
      ],
      "lonLat": [
        77.2425302,
        28.6608389
      ],
      "use": "holdout",
      "affineResidualM": 110.7,
      "affineLooErrorM": null
    },
    {
      "legend": 5,
      "name": "Red Fort Complex",
      "legendText": "Palace and Gardens",
      "pixel": [
        650.0,
        1000.0
      ],
      "lonLat": [
        77.2411136,
        28.6570302
      ],
      "use": "fit",
      "affineResidualM": 239.4,
      "affineLooErrorM": 316.6
    },
    {
      "legend": 6,
      "name": "Diwan-i-Khas",
      "legendText": "The Marble Hall or Throne-room",
      "pixel": [
        620.0,
        1090.0
      ],
      "lonLat": [
        77.2434025,
        28.6564776
      ],
      "use": "fit",
      "affineResidualM": 248.7,
      "affineLooErrorM": 334.4
    },
    {
      "legend": 10,
      "name": "Jama Masjid",
      "legendText": "The Jumma Musjid",
      "pixel": [
        1410.0,
        690.0
      ],
      "lonLat": [
        77.2334669,
        28.6506864
      ],
      "use": "fit",
      "affineResidualM": 134.8,
      "affineLooErrorM": 163.4
    },
    {
      "legend": 12,
      "name": "Fatehpuri Masjid",
      "legendText": "The Musjid Futipoor",
      "pixel": [
        2050.0,
        780.0
      ],
      "lonLat": [
        77.22263,
        28.6566802
      ],
      "use": "fit",
      "affineResidualM": 187.9,
      "affineLooErrorM": 286.3
    },
    {
      "legend": 14,
      "name": "Kashmiri Gate",
      "legendText": "Cashmere Gate",
      "pixel": [
        1435.0,
        1370.0
      ],
      "lonLat": [
        77.2290286,
        28.6665554
      ],
      "use": "fit",
      "affineResidualM": 126.1,
      "affineLooErrorM": 201.7
    },
    {
      "legend": 20,
      "name": "Ajmeri Gate",
      "legendText": "Ajmere Gate",
      "pixel": [
        2190.0,
        455.0
      ],
      "lonLat": [
        77.224004,
        28.646253
      ],
      "use": "fit",
      "affineResidualM": 171.5,
      "affineLooErrorM": 374.3
    },
    {
      "legend": 22,
      "name": "Delhi Gate",
      "legendText": "Delhi Gate",
      "pixel": [
        658.0,
        495.0
      ],
      "lonLat": [
        77.2405641,
        28.6411807
      ],
      "use": "fit",
      "affineResidualM": 225.2,
      "affineLooErrorM": 546.4
    },
    {
      "legend": 25,
      "name": "Saint James Anglican Church",
      "legendText": "English Church",
      "pixel": [
        1245.0,
        1255.0
      ],
      "lonLat": [
        77.2310777,
        28.6657462
      ],
      "use": "fit",
      "affineResidualM": 232.9,
      "affineLooErrorM": 301.3
    },
    {
      "legend": 26,
      "name": "Old Magazine complex",
      "legendText": "Magazine and Store Houses",
      "pixel": [
        985.0,
        1300.0
      ],
      "lonLat": [
        77.2350235,
        28.6617947
      ],
      "use": "fit",
      "affineResidualM": 243.2,
      "affineLooErrorM": 324.3
    }
  ],
  "metrics": {
    "affineLooRmseM": 332.6529272895172,
    "naturalLooRmseM": 331.9511817002794,
    "affineHoldoutM": 110.6618832102688,
    "naturalHoldoutM": 138.98806773096965
  }
});
