---
title: "CV"
pagetitle: CV
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<br>

[Here](https://www.dropbox.com/s/oxr6pj6yskpautr/CV%20Abhishek%20Arora_2022.pdf?dl=0) is my complete CV.

<br>

### Education

 - 2018-2020 - Master of Arts in Economics, Delhi School of Economics, Delhi University
 
 - 2015-2018 - Bachelor of Management Studies (Finance), Shaheed Sukhdev College of Business Studies, Delhi University

<br>

### Research-related experience

- 2022-Present - Pre-doctoral Fellow, Department of Economics, Harvard University with Prof. Melissa Dell

- 2021-2022 - Research Assistant, World Bank with Dr. Vijayendra Rao, Dr. Siddharth George and Dr. M. R. Sharan , currently co-authoring with them on various projects

- 2020-2021 - Research Assistant, Indian Statistical Institute (Delhi)  with Dr. Farzana Afridi and Dr. Kanika Mahajan 

- 2019-2020 - Research Assistant, Delhi School of Economics  with Prof. J.V. Meenakshi

- 2020 - Research Assistant , King's College London with Prof. Amrita Dhillon, Dr Sunil Mitra Kumar, Prof. Louise Tillin

<br>

### Other Professional Exeperience

- 2020 - (Short-Term), Analyst, Bain Capability Centre

- 2019 - Intern, Procter and Gamble

- 2017 - Intern, NITI Aayog (Erstwhile Planning Comission of India)

<br>

### Conferences and Workshops

- 2022 - Yale Economic Growth Center, Inclusion Economics Gender Brown Bag

- 2022 - World Bank, 9th South Asia Economic Policy Network Conference

- 2022 - NCAER, Seminar    

- 2022 - Indian School of Business, Seminar

- 2022 - 17th Annual Conference on Economic Growth and Development, ISI, Delhi 

- 2022 - NUS Applied Micro SIG 

- 2022 - Annual Economics Conference, Ashoka University (KA)

- 2023 - University of Oxford, Seminar



<br>
